#####################################
# Settings
#####################################

# Overwrite, Error
conflictResolution: Overwrite

tableInfo:
  databases: "./workspace/databases.json"
  outputDirectory: "./workspace"

generate:
  tableFiles: ["./workspace/tables/generated1.json", "./workspace/tables/generated2.json"]
  ignoreTables: ["schema_version", "flyway_schema_history"]

  template: "./workspace/templates/ScalaCaseClassSample.vm"
  constants: "./workspace/constants.json"
  mapping: "./workspace/mapping.json"
  outputDirectory: "./.dist"
  fileName:
    pattern: "${tableName}.scala"
    tableName:
      # UpperCamel, lowerCamel, UPPER_SNAKE, lower_snake, UPPER-KEBAB, lower-kebab
      caseStyle: UpperCamel
      # singularize, pluralize, none
      inflector: singularize
